USE master
GO
IF EXISTS(SELECT * FROM sys.databases WHERE NAME = 'VolunteerCampaignDB')
DROP DATABASE VolunteerCampaignDB
GO

CREATE DATABASE VolunteerCampaignDB
GO

USE VolunteerCampaignDB
GO

--CD (ID, NGAYBATDAU, THOIGIAN, YNGHIA, MOREINFO)
	--DOI (ID, IDDOI, IDCD, SOLUONGNGUOI)
		--SV (ID, IDDOI, MSSV, TEN, NGAYSINH, LOP, NGAYVAODOAN, DIEMTB, MOREINFO)
		--GV (ID, IDDOI, TEN, NGAYSINH, MOREINFO)
			
	

--CHIEN DICH
CREATE TABLE CHIENDICH
(
	Id CHAR(10) PRIMARY KEY NOT NULL, --eg: GSVC2017, SVC2017
	
	Ten NVARCHAR(100) NOT NULL, 
	NgayBatDau DATE NOT NULL DEFAULT GETDATE(),
	ThoiGian INT NOT NULL,
	YNghia NVARCHAR(100),
	SoLuongNguoiCan INT NOT NULL DEFAULT 0,
	SoLuongNguoiThamGia INT NOT NULL DEFAULT 0,
	NgayHetHan DATE NOT NULl DEFAULT GETDATE() + 30,
	MoreInfo NTEXT DEFAULT NULL,

	CONSTRAINT chkThoiGianThucHienCD CHECK (ThoiGian > 0),
	CONSTRAINT chkSoLuongNguoiCan CHECK (SoLuongNguoiCan >= 0),
	CONSTRAINT chkSoLuongNguoiThamGia CHECK (SoLuongNguoiThamGia >= 0)
)
GO

--CONG VIEC 
CREATE TABLE CONGVIEC
(
	Id CHAR(13) PRIMARY KEY NOT NULL, --eg: GS2017DAL, S2017DN. 
	IdCD CHAR(10) NOT NULL,
	
	TenCV NVARCHAR(100) NOT NULL,
	DiaDiem NVARCHAR(100) NOT NULL,
	NoiDung NVARCHAR(100),
	SoLuongNguoi INT NOT NULL,
	NgayBatDau DATETIME NOT NULL DEFAULT GETDATE(),
	ThoiGian INT NOT NULL,
	ChiPhiMotNguoi MONEY NOT NULL,
	MoreInfo NTEXT DEFAULT NULL,

	CONSTRAINT chkThoiGianThucHienCV CHECK (ThoiGian > 0),

	FOREIGN KEY (IdCD) REFERENCES dbo.CHIENDICH(Id)
)
GO

--DOI
CREATE TABLE DOI
(
	Id CHAR(13) PRIMARY KEY NOT NULL, --eg: 'IdCD' + '-01' : GSVC2017-01
	IdCD CHAR(10) NOT NULL,

	SoLuongThanhVien INT NOT NULL DEFAULT 0,
	SoLuongThanhVienThamGia INT NOT NULL DEFAULT 0,

	CONSTRAINT chkSoLuongThanhVien CHECK (SoLuongThanhVien >= 0),

	FOREIGN KEY (IdCD) REFERENCES dbo.CHIENDICH(Id)
)
GO

--SV
CREATE TABLE SINHVIEN
(
	Id CHAR(10) PRIMARY KEY NOT NULL, --eg: 15DH110215
	IdCD CHAR(10) NOT NULL,
	IdDoi CHAR(13) NOT NULL,

	Ten NVARCHAR(50) NOT NULL, 
	NgaySinh DATE NOT NULL,
	GioiTinh CHAR(1) NOT NULL, --M: NAM, F: NU
	SDT VARCHAR(15) NOT NULL,

	Lop CHAR(6) NOT NULL,
	NgayVaoDoan DATE DEFAULT NULL,
	DiemTB FLOAT NOT NULL DEFAULT 0,


	CONSTRAINT chkDiemTB CHECK (DiemTB >= 3),

	FOREIGN KEY (IdCD) REFERENCES dbo.CHIENDICH(Id),
	FOREIGN KEY (IdDoi) REFERENCES dbo.DOI(Id),
)
GO

--GV
CREATE TABLE GIANGVIEN
(
	Id CHAR(10) PRIMARY KEY NOT NULL, 
	IdCD CHAR(10) NOT NULL,
	IdDoi CHAR(13) NOT NULL,
	
	Ten NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh CHAR(1) NOT NULL, --M: NAM, F: NU
	SDT VARCHAR(15) NOT NULL,

	Khoa NVARCHAR(50),

	FOREIGN KEY (IdCD) REFERENCES dbo.CHIENDICH(Id),
	FOREIGN KEY (IdDoi) REFERENCES dbo.DOI(Id),
)
GO

--CHI TIET CONG VIEC
CREATE TABLE CTCONGVIEC
(
	IdCV CHAR(13) NOT NULL,
	IdDoi CHAR(13) NOT NULL,
	KetQuaCV CHAR(1) NOT NULL, --eg: 2: Tot, 1: Hoan Thanh, 0: Chua Dat.
	HinhAnh VARCHAR(500) DEFAULT NULL,

	PRIMARY KEY(IdCV, IdDoi),

	FOREIGN KEY (IdCV) REFERENCES dbo.CONGVIEC(Id),
	FOREIGN KEY (IdDoi) REFERENCES dbo.DOI(Id)
)
GO


--PHIEU THANH TOAN
CREATE TABLE PHIEUTHANHTOAN
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IdCD CHAR(10) NOT NULL,

	ChiPhiDuDinh FLOAT NOT NULL DEFAULT 0,
	CHiPhiPhatSinh FLOAT NOT NULL DEFAULT 0,
	TongChiPhi FLOAT NOT NULL DEFAULT 0,

	CONSTRAINT chkChiPhiDuDinh CHECK (ChiPhiDuDinh >= 0),
	CONSTRAINT chkCHiPhiPhatSinh CHECK (CHiPhiPhatSinh >= 0),
	CONSTRAINT chkTongChiPhi CHECK (TongChiPhi >= 0),

	FOREIGN KEY (IdCD) REFERENCES dbo.CHIENDICH(Id)
)
GO


--CHI PHI PHAT SINH
CREATE TABLE CHIPHIPHATSINH
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IdPhieuThanhToan INT NOT NULL,
	IdCV CHAR(13) NOT NULL,

	Ten NVARCHAR(20) NOT NULL,
	LyDo NTEXT DEFAULT NULL,
	ChungTu VARCHAR(50) DEFAULT NULL,
	DonGia FLOAT DEFAULT 0,

	CONSTRAINT chkDonGia CHECK (DonGia >= 0),

	FOREIGN KEY (IdPhieuThanhToan) REFERENCES dbo.PHIEUTHANHTOAN(Id),
	FOREIGN KEY (IdCV) REFERENCES dbo.CONGVIEC(Id)
)
GO

--CHUC VU
CREATE TABLE CHUCVU
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,

	Ten NVARCHAR(20) NOT NULL,
	Luong FLOAT NOT NULL DEFAULT 0,
	QuyenHan VARCHAR(50) DEFAULT NULL,

	CONSTRAINT chkLuong CHECK (Luong >= 0)
)
GO


--NHAN VIEN
CREATE TABLE NHANVIEN
(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IdChucVu INT NOT NULL,

	Ten NVARCHAR(50) NOT NULL,
	Mail NVARCHAR(30) DEFAULT NULL,
	SDT VARCHAR(15) NOT NULL,
	UserName VARCHAR(20) NOT NULL,
	Pwrd VARCHAR(20) NOT NULL,

	FOREIGN KEY (IdChucVu) REFERENCES dbo.CHUCVU(Id)
)
GO

--------------------------------INSERT VALUES----------------------------------
--USE VolunteerCampaignDB
--GO
SELECT * FROM CHIENDICH
SELECT * FROM CONGVIEC 
SELECT * FROM CTCONGVIEC
SELECT * FROM SINHVIEN
SELECT * FROM GIANGVIEN
SELECT * FROM DOI
SELECT * FROM CHIPHIPHATSINH
SELECT * FROM PHIEUTHANHTOAN
SELECT * FROM CHUCVU
SELECT * FROM NHANVIEN

INSERT INTO CHUCVU VALUES('Admin','500000','Admin stuffs')
INSERT INTO NHANVIEN VALUES(1,'Admin','Admin@gmail.com','090942131','admin','admin')

