#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerCampaignWebsite.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VolunteerCampaignDB")]
	public partial class CampaignDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHIENDICH(CHIENDICH instance);
    partial void UpdateCHIENDICH(CHIENDICH instance);
    partial void DeleteCHIENDICH(CHIENDICH instance);
    partial void InsertCHIPHIPHATSINH(CHIPHIPHATSINH instance);
    partial void UpdateCHIPHIPHATSINH(CHIPHIPHATSINH instance);
    partial void DeleteCHIPHIPHATSINH(CHIPHIPHATSINH instance);
    partial void InsertCTCONGVIEC(CTCONGVIEC instance);
    partial void UpdateCTCONGVIEC(CTCONGVIEC instance);
    partial void DeleteCTCONGVIEC(CTCONGVIEC instance);
    partial void InsertCONGVIEC(CONGVIEC instance);
    partial void UpdateCONGVIEC(CONGVIEC instance);
    partial void DeleteCONGVIEC(CONGVIEC instance);
    partial void InsertGIANGVIEN(GIANGVIEN instance);
    partial void UpdateGIANGVIEN(GIANGVIEN instance);
    partial void DeleteGIANGVIEN(GIANGVIEN instance);
    partial void InsertSINHVIEN(SINHVIEN instance);
    partial void UpdateSINHVIEN(SINHVIEN instance);
    partial void DeleteSINHVIEN(SINHVIEN instance);
    partial void InsertDOI(DOI instance);
    partial void UpdateDOI(DOI instance);
    partial void DeleteDOI(DOI instance);
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHIEUTHANHTOAN(PHIEUTHANHTOAN instance);
    partial void UpdatePHIEUTHANHTOAN(PHIEUTHANHTOAN instance);
    partial void DeletePHIEUTHANHTOAN(PHIEUTHANHTOAN instance);
    #endregion
		
		public CampaignDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VolunteerCampaignDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CampaignDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CampaignDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CampaignDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CampaignDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHIENDICH> CHIENDICHes
		{
			get
			{
				return this.GetTable<CHIENDICH>();
			}
		}
		
		public System.Data.Linq.Table<CHIPHIPHATSINH> CHIPHIPHATSINHs
		{
			get
			{
				return this.GetTable<CHIPHIPHATSINH>();
			}
		}
		
		public System.Data.Linq.Table<CTCONGVIEC> CTCONGVIECs
		{
			get
			{
				return this.GetTable<CTCONGVIEC>();
			}
		}
		
		public System.Data.Linq.Table<CONGVIEC> CONGVIECs
		{
			get
			{
				return this.GetTable<CONGVIEC>();
			}
		}
		
		public System.Data.Linq.Table<GIANGVIEN> GIANGVIENs
		{
			get
			{
				return this.GetTable<GIANGVIEN>();
			}
		}
		
		public System.Data.Linq.Table<SINHVIEN> SINHVIENs
		{
			get
			{
				return this.GetTable<SINHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<DOI> DOIs
		{
			get
			{
				return this.GetTable<DOI>();
			}
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTHANHTOAN> PHIEUTHANHTOANs
		{
			get
			{
				return this.GetTable<PHIEUTHANHTOAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHIENDICH")]
	public partial class CHIENDICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _Ten;
		
		private System.DateTime _NgayBatDau;
		
		private int _ThoiGian;
		
		private string _YNghia;
		
		private int _SoLuongNguoiCan;
		
		private int _SoLuongNguoiThamGia;
		
		private System.DateTime _NgayHetHan;
		
		private string _MoreInfo;
		
		private EntitySet<CONGVIEC> _CONGVIECs;
		
		private EntitySet<GIANGVIEN> _GIANGVIENs;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
		private EntitySet<DOI> _DOIs;
		
		private EntitySet<PHIEUTHANHTOAN> _PHIEUTHANHTOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNgayBatDauChanging(System.DateTime value);
    partial void OnNgayBatDauChanged();
    partial void OnThoiGianChanging(int value);
    partial void OnThoiGianChanged();
    partial void OnYNghiaChanging(string value);
    partial void OnYNghiaChanged();
    partial void OnSoLuongNguoiCanChanging(int value);
    partial void OnSoLuongNguoiCanChanged();
    partial void OnSoLuongNguoiThamGiaChanging(int value);
    partial void OnSoLuongNguoiThamGiaChanged();
    partial void OnNgayHetHanChanging(System.DateTime value);
    partial void OnNgayHetHanChanged();
    partial void OnMoreInfoChanging(string value);
    partial void OnMoreInfoChanged();
    #endregion
		
		public CHIENDICH()
		{
			this._CONGVIECs = new EntitySet<CONGVIEC>(new Action<CONGVIEC>(this.attach_CONGVIECs), new Action<CONGVIEC>(this.detach_CONGVIECs));
			this._GIANGVIENs = new EntitySet<GIANGVIEN>(new Action<GIANGVIEN>(this.attach_GIANGVIENs), new Action<GIANGVIEN>(this.detach_GIANGVIENs));
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			this._DOIs = new EntitySet<DOI>(new Action<DOI>(this.attach_DOIs), new Action<DOI>(this.detach_DOIs));
			this._PHIEUTHANHTOANs = new EntitySet<PHIEUTHANHTOAN>(new Action<PHIEUTHANHTOAN>(this.attach_PHIEUTHANHTOANs), new Action<PHIEUTHANHTOAN>(this.detach_PHIEUTHANHTOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="Date NOT NULL")]
		public System.DateTime NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="Int NOT NULL")]
		public int ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YNghia", DbType="NVarChar(100)")]
		public string YNghia
		{
			get
			{
				return this._YNghia;
			}
			set
			{
				if ((this._YNghia != value))
				{
					this.OnYNghiaChanging(value);
					this.SendPropertyChanging();
					this._YNghia = value;
					this.SendPropertyChanged("YNghia");
					this.OnYNghiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNguoiCan", DbType="Int NOT NULL")]
		public int SoLuongNguoiCan
		{
			get
			{
				return this._SoLuongNguoiCan;
			}
			set
			{
				if ((this._SoLuongNguoiCan != value))
				{
					this.OnSoLuongNguoiCanChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNguoiCan = value;
					this.SendPropertyChanged("SoLuongNguoiCan");
					this.OnSoLuongNguoiCanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNguoiThamGia", DbType="Int NOT NULL")]
		public int SoLuongNguoiThamGia
		{
			get
			{
				return this._SoLuongNguoiThamGia;
			}
			set
			{
				if ((this._SoLuongNguoiThamGia != value))
				{
					this.OnSoLuongNguoiThamGiaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNguoiThamGia = value;
					this.SendPropertyChanged("SoLuongNguoiThamGia");
					this.OnSoLuongNguoiThamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="Date NOT NULL")]
		public System.DateTime NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoreInfo", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoreInfo
		{
			get
			{
				return this._MoreInfo;
			}
			set
			{
				if ((this._MoreInfo != value))
				{
					this.OnMoreInfoChanging(value);
					this.SendPropertyChanging();
					this._MoreInfo = value;
					this.SendPropertyChanged("MoreInfo");
					this.OnMoreInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHIENDICH_CONGVIEC", Storage="_CONGVIECs", ThisKey="Id", OtherKey="IdCD")]
		public EntitySet<CONGVIEC> CONGVIECs
		{
			get
			{
				return this._CONGVIECs;
			}
			set
			{
				this._CONGVIECs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHIENDICH_GIANGVIEN", Storage="_GIANGVIENs", ThisKey="Id", OtherKey="IdCD")]
		public EntitySet<GIANGVIEN> GIANGVIENs
		{
			get
			{
				return this._GIANGVIENs;
			}
			set
			{
				this._GIANGVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHIENDICH_SINHVIEN", Storage="_SINHVIENs", ThisKey="Id", OtherKey="IdCD")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHIENDICH_DOI", Storage="_DOIs", ThisKey="Id", OtherKey="IdCD")]
		public EntitySet<DOI> DOIs
		{
			get
			{
				return this._DOIs;
			}
			set
			{
				this._DOIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHIENDICH_PHIEUTHANHTOAN", Storage="_PHIEUTHANHTOANs", ThisKey="Id", OtherKey="IdCD")]
		public EntitySet<PHIEUTHANHTOAN> PHIEUTHANHTOANs
		{
			get
			{
				return this._PHIEUTHANHTOANs;
			}
			set
			{
				this._PHIEUTHANHTOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONGVIECs(CONGVIEC entity)
		{
			this.SendPropertyChanging();
			entity.CHIENDICH = this;
		}
		
		private void detach_CONGVIECs(CONGVIEC entity)
		{
			this.SendPropertyChanging();
			entity.CHIENDICH = null;
		}
		
		private void attach_GIANGVIENs(GIANGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHIENDICH = this;
		}
		
		private void detach_GIANGVIENs(GIANGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHIENDICH = null;
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHIENDICH = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHIENDICH = null;
		}
		
		private void attach_DOIs(DOI entity)
		{
			this.SendPropertyChanging();
			entity.CHIENDICH = this;
		}
		
		private void detach_DOIs(DOI entity)
		{
			this.SendPropertyChanging();
			entity.CHIENDICH = null;
		}
		
		private void attach_PHIEUTHANHTOANs(PHIEUTHANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.CHIENDICH = this;
		}
		
		private void detach_PHIEUTHANHTOANs(PHIEUTHANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.CHIENDICH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHIPHIPHATSINH")]
	public partial class CHIPHIPHATSINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdPhieuThanhToan;
		
		private string _IdCV;
		
		private string _Ten;
		
		private string _LyDo;
		
		private string _ChungTu;
		
		private System.Nullable<double> _DonGia;
		
		private EntityRef<CONGVIEC> _CONGVIEC;
		
		private EntityRef<PHIEUTHANHTOAN> _PHIEUTHANHTOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdPhieuThanhToanChanging(int value);
    partial void OnIdPhieuThanhToanChanged();
    partial void OnIdCVChanging(string value);
    partial void OnIdCVChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnLyDoChanging(string value);
    partial void OnLyDoChanged();
    partial void OnChungTuChanging(string value);
    partial void OnChungTuChanged();
    partial void OnDonGiaChanging(System.Nullable<double> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public CHIPHIPHATSINH()
		{
			this._CONGVIEC = default(EntityRef<CONGVIEC>);
			this._PHIEUTHANHTOAN = default(EntityRef<PHIEUTHANHTOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieuThanhToan", DbType="Int NOT NULL")]
		public int IdPhieuThanhToan
		{
			get
			{
				return this._IdPhieuThanhToan;
			}
			set
			{
				if ((this._IdPhieuThanhToan != value))
				{
					if (this._PHIEUTHANHTOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPhieuThanhToanChanging(value);
					this.SendPropertyChanging();
					this._IdPhieuThanhToan = value;
					this.SendPropertyChanged("IdPhieuThanhToan");
					this.OnIdPhieuThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCV", DbType="Char(13) NOT NULL", CanBeNull=false)]
		public string IdCV
		{
			get
			{
				return this._IdCV;
			}
			set
			{
				if ((this._IdCV != value))
				{
					if (this._CONGVIEC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCVChanging(value);
					this.SendPropertyChanging();
					this._IdCV = value;
					this.SendPropertyChanged("IdCV");
					this.OnIdCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDo", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LyDo
		{
			get
			{
				return this._LyDo;
			}
			set
			{
				if ((this._LyDo != value))
				{
					this.OnLyDoChanging(value);
					this.SendPropertyChanging();
					this._LyDo = value;
					this.SendPropertyChanged("LyDo");
					this.OnLyDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChungTu", DbType="VarChar(50)")]
		public string ChungTu
		{
			get
			{
				return this._ChungTu;
			}
			set
			{
				if ((this._ChungTu != value))
				{
					this.OnChungTuChanging(value);
					this.SendPropertyChanging();
					this._ChungTu = value;
					this.SendPropertyChanged("ChungTu");
					this.OnChungTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float")]
		public System.Nullable<double> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGVIEC_CHIPHIPHATSINH", Storage="_CONGVIEC", ThisKey="IdCV", OtherKey="Id", IsForeignKey=true)]
		public CONGVIEC CONGVIEC
		{
			get
			{
				return this._CONGVIEC.Entity;
			}
			set
			{
				CONGVIEC previousValue = this._CONGVIEC.Entity;
				if (((previousValue != value) 
							|| (this._CONGVIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CONGVIEC.Entity = null;
						previousValue.CHIPHIPHATSINHs.Remove(this);
					}
					this._CONGVIEC.Entity = value;
					if ((value != null))
					{
						value.CHIPHIPHATSINHs.Add(this);
						this._IdCV = value.Id;
					}
					else
					{
						this._IdCV = default(string);
					}
					this.SendPropertyChanged("CONGVIEC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUTHANHTOAN_CHIPHIPHATSINH", Storage="_PHIEUTHANHTOAN", ThisKey="IdPhieuThanhToan", OtherKey="Id", IsForeignKey=true)]
		public PHIEUTHANHTOAN PHIEUTHANHTOAN
		{
			get
			{
				return this._PHIEUTHANHTOAN.Entity;
			}
			set
			{
				PHIEUTHANHTOAN previousValue = this._PHIEUTHANHTOAN.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUTHANHTOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUTHANHTOAN.Entity = null;
						previousValue.CHIPHIPHATSINHs.Remove(this);
					}
					this._PHIEUTHANHTOAN.Entity = value;
					if ((value != null))
					{
						value.CHIPHIPHATSINHs.Add(this);
						this._IdPhieuThanhToan = value.Id;
					}
					else
					{
						this._IdPhieuThanhToan = default(int);
					}
					this.SendPropertyChanged("PHIEUTHANHTOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTCONGVIEC")]
	public partial class CTCONGVIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdCV;
		
		private string _IdDoi;
		
		private char _KetQuaCV;
		
		private string _HinhAnh;
		
		private EntityRef<CONGVIEC> _CONGVIEC;
		
		private EntityRef<DOI> _DOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCVChanging(string value);
    partial void OnIdCVChanged();
    partial void OnIdDoiChanging(string value);
    partial void OnIdDoiChanged();
    partial void OnKetQuaCVChanging(char value);
    partial void OnKetQuaCVChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    #endregion
		
		public CTCONGVIEC()
		{
			this._CONGVIEC = default(EntityRef<CONGVIEC>);
			this._DOI = default(EntityRef<DOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCV", DbType="Char(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdCV
		{
			get
			{
				return this._IdCV;
			}
			set
			{
				if ((this._IdCV != value))
				{
					if (this._CONGVIEC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCVChanging(value);
					this.SendPropertyChanging();
					this._IdCV = value;
					this.SendPropertyChanged("IdCV");
					this.OnIdCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDoi", DbType="Char(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdDoi
		{
			get
			{
				return this._IdDoi;
			}
			set
			{
				if ((this._IdDoi != value))
				{
					if (this._DOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdDoiChanging(value);
					this.SendPropertyChanging();
					this._IdDoi = value;
					this.SendPropertyChanged("IdDoi");
					this.OnIdDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetQuaCV", DbType="Char(1) NOT NULL")]
		public char KetQuaCV
		{
			get
			{
				return this._KetQuaCV;
			}
			set
			{
				if ((this._KetQuaCV != value))
				{
					this.OnKetQuaCVChanging(value);
					this.SendPropertyChanging();
					this._KetQuaCV = value;
					this.SendPropertyChanged("KetQuaCV");
					this.OnKetQuaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGVIEC_CTCONGVIEC", Storage="_CONGVIEC", ThisKey="IdCV", OtherKey="Id", IsForeignKey=true)]
		public CONGVIEC CONGVIEC
		{
			get
			{
				return this._CONGVIEC.Entity;
			}
			set
			{
				CONGVIEC previousValue = this._CONGVIEC.Entity;
				if (((previousValue != value) 
							|| (this._CONGVIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CONGVIEC.Entity = null;
						previousValue.CTCONGVIECs.Remove(this);
					}
					this._CONGVIEC.Entity = value;
					if ((value != null))
					{
						value.CTCONGVIECs.Add(this);
						this._IdCV = value.Id;
					}
					else
					{
						this._IdCV = default(string);
					}
					this.SendPropertyChanged("CONGVIEC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOI_CTCONGVIEC", Storage="_DOI", ThisKey="IdDoi", OtherKey="Id", IsForeignKey=true)]
		public DOI DOI
		{
			get
			{
				return this._DOI.Entity;
			}
			set
			{
				DOI previousValue = this._DOI.Entity;
				if (((previousValue != value) 
							|| (this._DOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOI.Entity = null;
						previousValue.CTCONGVIECs.Remove(this);
					}
					this._DOI.Entity = value;
					if ((value != null))
					{
						value.CTCONGVIECs.Add(this);
						this._IdDoi = value.Id;
					}
					else
					{
						this._IdDoi = default(string);
					}
					this.SendPropertyChanged("DOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONGVIEC")]
	public partial class CONGVIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _IdCD;
		
		private string _TenCV;
		
		private string _DiaDiem;
		
		private string _NoiDung;
		
		private int _SoLuongNguoi;
		
		private System.DateTime _NgayBatDau;
		
		private int _ThoiGian;
		
		private decimal _ChiPhiMotNguoi;
		
		private string _MoreInfo;
		
		private EntitySet<CHIPHIPHATSINH> _CHIPHIPHATSINHs;
		
		private EntitySet<CTCONGVIEC> _CTCONGVIECs;
		
		private EntityRef<CHIENDICH> _CHIENDICH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnIdCDChanging(string value);
    partial void OnIdCDChanged();
    partial void OnTenCVChanging(string value);
    partial void OnTenCVChanged();
    partial void OnDiaDiemChanging(string value);
    partial void OnDiaDiemChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnSoLuongNguoiChanging(int value);
    partial void OnSoLuongNguoiChanged();
    partial void OnNgayBatDauChanging(System.DateTime value);
    partial void OnNgayBatDauChanged();
    partial void OnThoiGianChanging(int value);
    partial void OnThoiGianChanged();
    partial void OnChiPhiMotNguoiChanging(decimal value);
    partial void OnChiPhiMotNguoiChanged();
    partial void OnMoreInfoChanging(string value);
    partial void OnMoreInfoChanged();
    #endregion
		
		public CONGVIEC()
		{
			this._CHIPHIPHATSINHs = new EntitySet<CHIPHIPHATSINH>(new Action<CHIPHIPHATSINH>(this.attach_CHIPHIPHATSINHs), new Action<CHIPHIPHATSINH>(this.detach_CHIPHIPHATSINHs));
			this._CTCONGVIECs = new EntitySet<CTCONGVIEC>(new Action<CTCONGVIEC>(this.attach_CTCONGVIECs), new Action<CTCONGVIEC>(this.detach_CTCONGVIECs));
			this._CHIENDICH = default(EntityRef<CHIENDICH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Char(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string IdCD
		{
			get
			{
				return this._IdCD;
			}
			set
			{
				if ((this._IdCD != value))
				{
					if (this._CHIENDICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCDChanging(value);
					this.SendPropertyChanging();
					this._IdCD = value;
					this.SendPropertyChanged("IdCD");
					this.OnIdCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenCV
		{
			get
			{
				return this._TenCV;
			}
			set
			{
				if ((this._TenCV != value))
				{
					this.OnTenCVChanging(value);
					this.SendPropertyChanging();
					this._TenCV = value;
					this.SendPropertyChanged("TenCV");
					this.OnTenCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this.OnDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem = value;
					this.SendPropertyChanged("DiaDiem");
					this.OnDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(100)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNguoi", DbType="Int NOT NULL")]
		public int SoLuongNguoi
		{
			get
			{
				return this._SoLuongNguoi;
			}
			set
			{
				if ((this._SoLuongNguoi != value))
				{
					this.OnSoLuongNguoiChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNguoi = value;
					this.SendPropertyChanged("SoLuongNguoi");
					this.OnSoLuongNguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="DateTime NOT NULL")]
		public System.DateTime NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="Int NOT NULL")]
		public int ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiPhiMotNguoi", DbType="Money NOT NULL")]
		public decimal ChiPhiMotNguoi
		{
			get
			{
				return this._ChiPhiMotNguoi;
			}
			set
			{
				if ((this._ChiPhiMotNguoi != value))
				{
					this.OnChiPhiMotNguoiChanging(value);
					this.SendPropertyChanging();
					this._ChiPhiMotNguoi = value;
					this.SendPropertyChanged("ChiPhiMotNguoi");
					this.OnChiPhiMotNguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoreInfo", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoreInfo
		{
			get
			{
				return this._MoreInfo;
			}
			set
			{
				if ((this._MoreInfo != value))
				{
					this.OnMoreInfoChanging(value);
					this.SendPropertyChanging();
					this._MoreInfo = value;
					this.SendPropertyChanged("MoreInfo");
					this.OnMoreInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGVIEC_CHIPHIPHATSINH", Storage="_CHIPHIPHATSINHs", ThisKey="Id", OtherKey="IdCV")]
		public EntitySet<CHIPHIPHATSINH> CHIPHIPHATSINHs
		{
			get
			{
				return this._CHIPHIPHATSINHs;
			}
			set
			{
				this._CHIPHIPHATSINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGVIEC_CTCONGVIEC", Storage="_CTCONGVIECs", ThisKey="Id", OtherKey="IdCV")]
		public EntitySet<CTCONGVIEC> CTCONGVIECs
		{
			get
			{
				return this._CTCONGVIECs;
			}
			set
			{
				this._CTCONGVIECs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHIENDICH_CONGVIEC", Storage="_CHIENDICH", ThisKey="IdCD", OtherKey="Id", IsForeignKey=true)]
		public CHIENDICH CHIENDICH
		{
			get
			{
				return this._CHIENDICH.Entity;
			}
			set
			{
				CHIENDICH previousValue = this._CHIENDICH.Entity;
				if (((previousValue != value) 
							|| (this._CHIENDICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHIENDICH.Entity = null;
						previousValue.CONGVIECs.Remove(this);
					}
					this._CHIENDICH.Entity = value;
					if ((value != null))
					{
						value.CONGVIECs.Add(this);
						this._IdCD = value.Id;
					}
					else
					{
						this._IdCD = default(string);
					}
					this.SendPropertyChanged("CHIENDICH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHIPHIPHATSINHs(CHIPHIPHATSINH entity)
		{
			this.SendPropertyChanging();
			entity.CONGVIEC = this;
		}
		
		private void detach_CHIPHIPHATSINHs(CHIPHIPHATSINH entity)
		{
			this.SendPropertyChanging();
			entity.CONGVIEC = null;
		}
		
		private void attach_CTCONGVIECs(CTCONGVIEC entity)
		{
			this.SendPropertyChanging();
			entity.CONGVIEC = this;
		}
		
		private void detach_CTCONGVIECs(CTCONGVIEC entity)
		{
			this.SendPropertyChanging();
			entity.CONGVIEC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIANGVIEN")]
	public partial class GIANGVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _IdCD;
		
		private string _IdDoi;
		
		private string _Ten;
		
		private System.DateTime _NgaySinh;
		
		private char _GioiTinh;
		
		private string _SDT;
		
		private string _Khoa;
		
		private EntityRef<CHIENDICH> _CHIENDICH;
		
		private EntityRef<DOI> _DOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnIdCDChanging(string value);
    partial void OnIdCDChanged();
    partial void OnIdDoiChanging(string value);
    partial void OnIdDoiChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(char value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnKhoaChanging(string value);
    partial void OnKhoaChanged();
    #endregion
		
		public GIANGVIEN()
		{
			this._CHIENDICH = default(EntityRef<CHIENDICH>);
			this._DOI = default(EntityRef<DOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string IdCD
		{
			get
			{
				return this._IdCD;
			}
			set
			{
				if ((this._IdCD != value))
				{
					if (this._CHIENDICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCDChanging(value);
					this.SendPropertyChanging();
					this._IdCD = value;
					this.SendPropertyChanged("IdCD");
					this.OnIdCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDoi", DbType="Char(13) NOT NULL", CanBeNull=false)]
		public string IdDoi
		{
			get
			{
				return this._IdDoi;
			}
			set
			{
				if ((this._IdDoi != value))
				{
					if (this._DOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdDoiChanging(value);
					this.SendPropertyChanging();
					this._IdDoi = value;
					this.SendPropertyChanged("IdDoi");
					this.OnIdDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Char(1) NOT NULL")]
		public char GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="NVarChar(50)")]
		public string Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					this.OnKhoaChanging(value);
					this.SendPropertyChanging();
					this._Khoa = value;
					this.SendPropertyChanged("Khoa");
					this.OnKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHIENDICH_GIANGVIEN", Storage="_CHIENDICH", ThisKey="IdCD", OtherKey="Id", IsForeignKey=true)]
		public CHIENDICH CHIENDICH
		{
			get
			{
				return this._CHIENDICH.Entity;
			}
			set
			{
				CHIENDICH previousValue = this._CHIENDICH.Entity;
				if (((previousValue != value) 
							|| (this._CHIENDICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHIENDICH.Entity = null;
						previousValue.GIANGVIENs.Remove(this);
					}
					this._CHIENDICH.Entity = value;
					if ((value != null))
					{
						value.GIANGVIENs.Add(this);
						this._IdCD = value.Id;
					}
					else
					{
						this._IdCD = default(string);
					}
					this.SendPropertyChanged("CHIENDICH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOI_GIANGVIEN", Storage="_DOI", ThisKey="IdDoi", OtherKey="Id", IsForeignKey=true)]
		public DOI DOI
		{
			get
			{
				return this._DOI.Entity;
			}
			set
			{
				DOI previousValue = this._DOI.Entity;
				if (((previousValue != value) 
							|| (this._DOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOI.Entity = null;
						previousValue.GIANGVIENs.Remove(this);
					}
					this._DOI.Entity = value;
					if ((value != null))
					{
						value.GIANGVIENs.Add(this);
						this._IdDoi = value.Id;
					}
					else
					{
						this._IdDoi = default(string);
					}
					this.SendPropertyChanged("DOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SINHVIEN")]
	public partial class SINHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _IdCD;
		
		private string _IdDoi;
		
		private string _Ten;
		
		private System.DateTime _NgaySinh;
		
		private char _GioiTinh;
		
		private string _SDT;
		
		private string _Lop;
		
		private System.Nullable<System.DateTime> _NgayVaoDoan;
		
		private double _DiemTB;
		
		private EntityRef<CHIENDICH> _CHIENDICH;
		
		private EntityRef<DOI> _DOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnIdCDChanging(string value);
    partial void OnIdCDChanged();
    partial void OnIdDoiChanging(string value);
    partial void OnIdDoiChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(char value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnLopChanging(string value);
    partial void OnLopChanged();
    partial void OnNgayVaoDoanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoDoanChanged();
    partial void OnDiemTBChanging(double value);
    partial void OnDiemTBChanged();
    #endregion
		
		public SINHVIEN()
		{
			this._CHIENDICH = default(EntityRef<CHIENDICH>);
			this._DOI = default(EntityRef<DOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string IdCD
		{
			get
			{
				return this._IdCD;
			}
			set
			{
				if ((this._IdCD != value))
				{
					if (this._CHIENDICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCDChanging(value);
					this.SendPropertyChanging();
					this._IdCD = value;
					this.SendPropertyChanged("IdCD");
					this.OnIdCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDoi", DbType="Char(13) NOT NULL", CanBeNull=false)]
		public string IdDoi
		{
			get
			{
				return this._IdDoi;
			}
			set
			{
				if ((this._IdDoi != value))
				{
					if (this._DOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdDoiChanging(value);
					this.SendPropertyChanging();
					this._IdDoi = value;
					this.SendPropertyChanged("IdDoi");
					this.OnIdDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Char(1) NOT NULL")]
		public char GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this.OnLopChanging(value);
					this.SendPropertyChanging();
					this._Lop = value;
					this.SendPropertyChanged("Lop");
					this.OnLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoDoan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayVaoDoan
		{
			get
			{
				return this._NgayVaoDoan;
			}
			set
			{
				if ((this._NgayVaoDoan != value))
				{
					this.OnNgayVaoDoanChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoDoan = value;
					this.SendPropertyChanged("NgayVaoDoan");
					this.OnNgayVaoDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemTB", DbType="Float NOT NULL")]
		public double DiemTB
		{
			get
			{
				return this._DiemTB;
			}
			set
			{
				if ((this._DiemTB != value))
				{
					this.OnDiemTBChanging(value);
					this.SendPropertyChanging();
					this._DiemTB = value;
					this.SendPropertyChanged("DiemTB");
					this.OnDiemTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHIENDICH_SINHVIEN", Storage="_CHIENDICH", ThisKey="IdCD", OtherKey="Id", IsForeignKey=true)]
		public CHIENDICH CHIENDICH
		{
			get
			{
				return this._CHIENDICH.Entity;
			}
			set
			{
				CHIENDICH previousValue = this._CHIENDICH.Entity;
				if (((previousValue != value) 
							|| (this._CHIENDICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHIENDICH.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._CHIENDICH.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._IdCD = value.Id;
					}
					else
					{
						this._IdCD = default(string);
					}
					this.SendPropertyChanged("CHIENDICH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOI_SINHVIEN", Storage="_DOI", ThisKey="IdDoi", OtherKey="Id", IsForeignKey=true)]
		public DOI DOI
		{
			get
			{
				return this._DOI.Entity;
			}
			set
			{
				DOI previousValue = this._DOI.Entity;
				if (((previousValue != value) 
							|| (this._DOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOI.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._DOI.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._IdDoi = value.Id;
					}
					else
					{
						this._IdDoi = default(string);
					}
					this.SendPropertyChanged("DOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOI")]
	public partial class DOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _IdCD;
		
		private int _SoLuongThanhVien;
		
		private System.Nullable<int> _SoLuongThanhVienThamGia;
		
		private EntitySet<CTCONGVIEC> _CTCONGVIECs;
		
		private EntitySet<GIANGVIEN> _GIANGVIENs;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
		private EntityRef<CHIENDICH> _CHIENDICH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnIdCDChanging(string value);
    partial void OnIdCDChanged();
    partial void OnSoLuongThanhVienChanging(int value);
    partial void OnSoLuongThanhVienChanged();
    partial void OnSoLuongThanhVienThamGiaChanging(System.Nullable<int> value);
    partial void OnSoLuongThanhVienThamGiaChanged();
    #endregion
		
		public DOI()
		{
			this._CTCONGVIECs = new EntitySet<CTCONGVIEC>(new Action<CTCONGVIEC>(this.attach_CTCONGVIECs), new Action<CTCONGVIEC>(this.detach_CTCONGVIECs));
			this._GIANGVIENs = new EntitySet<GIANGVIEN>(new Action<GIANGVIEN>(this.attach_GIANGVIENs), new Action<GIANGVIEN>(this.detach_GIANGVIENs));
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			this._CHIENDICH = default(EntityRef<CHIENDICH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Char(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string IdCD
		{
			get
			{
				return this._IdCD;
			}
			set
			{
				if ((this._IdCD != value))
				{
					if (this._CHIENDICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCDChanging(value);
					this.SendPropertyChanging();
					this._IdCD = value;
					this.SendPropertyChanged("IdCD");
					this.OnIdCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongThanhVien", DbType="Int NOT NULL")]
		public int SoLuongThanhVien
		{
			get
			{
				return this._SoLuongThanhVien;
			}
			set
			{
				if ((this._SoLuongThanhVien != value))
				{
					this.OnSoLuongThanhVienChanging(value);
					this.SendPropertyChanging();
					this._SoLuongThanhVien = value;
					this.SendPropertyChanged("SoLuongThanhVien");
					this.OnSoLuongThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongThanhVienThamGia", DbType="Int")]
		public System.Nullable<int> SoLuongThanhVienThamGia
		{
			get
			{
				return this._SoLuongThanhVienThamGia;
			}
			set
			{
				if ((this._SoLuongThanhVienThamGia != value))
				{
					this.OnSoLuongThanhVienThamGiaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongThanhVienThamGia = value;
					this.SendPropertyChanged("SoLuongThanhVienThamGia");
					this.OnSoLuongThanhVienThamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOI_CTCONGVIEC", Storage="_CTCONGVIECs", ThisKey="Id", OtherKey="IdDoi")]
		public EntitySet<CTCONGVIEC> CTCONGVIECs
		{
			get
			{
				return this._CTCONGVIECs;
			}
			set
			{
				this._CTCONGVIECs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOI_GIANGVIEN", Storage="_GIANGVIENs", ThisKey="Id", OtherKey="IdDoi")]
		public EntitySet<GIANGVIEN> GIANGVIENs
		{
			get
			{
				return this._GIANGVIENs;
			}
			set
			{
				this._GIANGVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOI_SINHVIEN", Storage="_SINHVIENs", ThisKey="Id", OtherKey="IdDoi")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHIENDICH_DOI", Storage="_CHIENDICH", ThisKey="IdCD", OtherKey="Id", IsForeignKey=true)]
		public CHIENDICH CHIENDICH
		{
			get
			{
				return this._CHIENDICH.Entity;
			}
			set
			{
				CHIENDICH previousValue = this._CHIENDICH.Entity;
				if (((previousValue != value) 
							|| (this._CHIENDICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHIENDICH.Entity = null;
						previousValue.DOIs.Remove(this);
					}
					this._CHIENDICH.Entity = value;
					if ((value != null))
					{
						value.DOIs.Add(this);
						this._IdCD = value.Id;
					}
					else
					{
						this._IdCD = default(string);
					}
					this.SendPropertyChanged("CHIENDICH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTCONGVIECs(CTCONGVIEC entity)
		{
			this.SendPropertyChanging();
			entity.DOI = this;
		}
		
		private void detach_CTCONGVIECs(CTCONGVIEC entity)
		{
			this.SendPropertyChanging();
			entity.DOI = null;
		}
		
		private void attach_GIANGVIENs(GIANGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DOI = this;
		}
		
		private void detach_GIANGVIENs(GIANGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DOI = null;
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DOI = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DOI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ten;
		
		private double _Luong;
		
		private string _QuyenHan;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnLuongChanging(double value);
    partial void OnLuongChanged();
    partial void OnQuyenHanChanging(string value);
    partial void OnQuyenHanChanged();
    #endregion
		
		public CHUCVU()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="Float NOT NULL")]
		public double Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenHan", DbType="VarChar(50)")]
		public string QuyenHan
		{
			get
			{
				return this._QuyenHan;
			}
			set
			{
				if ((this._QuyenHan != value))
				{
					this.OnQuyenHanChanging(value);
					this.SendPropertyChanging();
					this._QuyenHan = value;
					this.SendPropertyChanged("QuyenHan");
					this.OnQuyenHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIEN", Storage="_NHANVIENs", ThisKey="Id", OtherKey="IdChucVu")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdChucVu;
		
		private string _Ten;
		
		private string _Mail;
		
		private string _SDT;
		
		private string _UserName;
		
		private string _Pwrd;
		
		private EntityRef<CHUCVU> _CHUCVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdChucVuChanging(int value);
    partial void OnIdChucVuChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPwrdChanging(string value);
    partial void OnPwrdChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._CHUCVU = default(EntityRef<CHUCVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdChucVu", DbType="Int NOT NULL")]
		public int IdChucVu
		{
			get
			{
				return this._IdChucVu;
			}
			set
			{
				if ((this._IdChucVu != value))
				{
					if (this._CHUCVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChucVuChanging(value);
					this.SendPropertyChanging();
					this._IdChucVu = value;
					this.SendPropertyChanged("IdChucVu");
					this.OnIdChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(30)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pwrd", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Pwrd
		{
			get
			{
				return this._Pwrd;
			}
			set
			{
				if ((this._Pwrd != value))
				{
					this.OnPwrdChanging(value);
					this.SendPropertyChanging();
					this._Pwrd = value;
					this.SendPropertyChanged("Pwrd");
					this.OnPwrdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIEN", Storage="_CHUCVU", ThisKey="IdChucVu", OtherKey="Id", IsForeignKey=true)]
		public CHUCVU CHUCVU
		{
			get
			{
				return this._CHUCVU.Entity;
			}
			set
			{
				CHUCVU previousValue = this._CHUCVU.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._CHUCVU.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._IdChucVu = value.Id;
					}
					else
					{
						this._IdChucVu = default(int);
					}
					this.SendPropertyChanged("CHUCVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTHANHTOAN")]
	public partial class PHIEUTHANHTOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _IdCD;
		
		private double _ChiPhiDuDinh;
		
		private double _CHiPhiPhatSinh;
		
		private double _TongChiPhi;
		
		private EntitySet<CHIPHIPHATSINH> _CHIPHIPHATSINHs;
		
		private EntityRef<CHIENDICH> _CHIENDICH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdCDChanging(string value);
    partial void OnIdCDChanged();
    partial void OnChiPhiDuDinhChanging(double value);
    partial void OnChiPhiDuDinhChanged();
    partial void OnCHiPhiPhatSinhChanging(double value);
    partial void OnCHiPhiPhatSinhChanged();
    partial void OnTongChiPhiChanging(double value);
    partial void OnTongChiPhiChanged();
    #endregion
		
		public PHIEUTHANHTOAN()
		{
			this._CHIPHIPHATSINHs = new EntitySet<CHIPHIPHATSINH>(new Action<CHIPHIPHATSINH>(this.attach_CHIPHIPHATSINHs), new Action<CHIPHIPHATSINH>(this.detach_CHIPHIPHATSINHs));
			this._CHIENDICH = default(EntityRef<CHIENDICH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string IdCD
		{
			get
			{
				return this._IdCD;
			}
			set
			{
				if ((this._IdCD != value))
				{
					if (this._CHIENDICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCDChanging(value);
					this.SendPropertyChanging();
					this._IdCD = value;
					this.SendPropertyChanged("IdCD");
					this.OnIdCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiPhiDuDinh", DbType="Float NOT NULL")]
		public double ChiPhiDuDinh
		{
			get
			{
				return this._ChiPhiDuDinh;
			}
			set
			{
				if ((this._ChiPhiDuDinh != value))
				{
					this.OnChiPhiDuDinhChanging(value);
					this.SendPropertyChanging();
					this._ChiPhiDuDinh = value;
					this.SendPropertyChanged("ChiPhiDuDinh");
					this.OnChiPhiDuDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHiPhiPhatSinh", DbType="Float NOT NULL")]
		public double CHiPhiPhatSinh
		{
			get
			{
				return this._CHiPhiPhatSinh;
			}
			set
			{
				if ((this._CHiPhiPhatSinh != value))
				{
					this.OnCHiPhiPhatSinhChanging(value);
					this.SendPropertyChanging();
					this._CHiPhiPhatSinh = value;
					this.SendPropertyChanged("CHiPhiPhatSinh");
					this.OnCHiPhiPhatSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongChiPhi", DbType="Float NOT NULL")]
		public double TongChiPhi
		{
			get
			{
				return this._TongChiPhi;
			}
			set
			{
				if ((this._TongChiPhi != value))
				{
					this.OnTongChiPhiChanging(value);
					this.SendPropertyChanging();
					this._TongChiPhi = value;
					this.SendPropertyChanged("TongChiPhi");
					this.OnTongChiPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUTHANHTOAN_CHIPHIPHATSINH", Storage="_CHIPHIPHATSINHs", ThisKey="Id", OtherKey="IdPhieuThanhToan")]
		public EntitySet<CHIPHIPHATSINH> CHIPHIPHATSINHs
		{
			get
			{
				return this._CHIPHIPHATSINHs;
			}
			set
			{
				this._CHIPHIPHATSINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHIENDICH_PHIEUTHANHTOAN", Storage="_CHIENDICH", ThisKey="IdCD", OtherKey="Id", IsForeignKey=true)]
		public CHIENDICH CHIENDICH
		{
			get
			{
				return this._CHIENDICH.Entity;
			}
			set
			{
				CHIENDICH previousValue = this._CHIENDICH.Entity;
				if (((previousValue != value) 
							|| (this._CHIENDICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHIENDICH.Entity = null;
						previousValue.PHIEUTHANHTOANs.Remove(this);
					}
					this._CHIENDICH.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHANHTOANs.Add(this);
						this._IdCD = value.Id;
					}
					else
					{
						this._IdCD = default(string);
					}
					this.SendPropertyChanged("CHIENDICH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHIPHIPHATSINHs(CHIPHIPHATSINH entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUTHANHTOAN = this;
		}
		
		private void detach_CHIPHIPHATSINHs(CHIPHIPHATSINH entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUTHANHTOAN = null;
		}
	}
}
#pragma warning restore 1591
